import AppKit
import Combine

final class ClipboardProvider: ObservableObject {
    struct Entry: Identifiable, Equatable {
        let id = UUID()
        let text: String
        let at: Date
    }

    @Published private(set) var items: [Entry] = []

    private(set) var limit = 3

    func setLimit(_ new: Int) {
        limit = max(1, new)
        if items.count > limit { items.removeLast(items.count - limit) }
    }
    private let board = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?

    private static let skipped: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init() {
        lastChange = board.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            self?.check()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() { items = [] }

    func copyBack(_ entry: Entry) {
        board.clearContents()
        board.setString(entry.text, forType: .string)
        lastChange = board.changeCount
    }

    private func check() {
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount

        let types = board.types ?? []
        guard !Self.skipped.contains(where: types.contains) else { return }

        guard let raw = board.string(forType: .string) else { return }
        let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return }

        items.removeAll { $0.text == text }
        items.insert(Entry(text: text, at: Date()), at: 0)
        if items.count > limit { items.removeLast(items.count - limit) }
    }
}
